### ISSUE TITLE
FillObjectBMI example not working in a Debug build

### ISSUE THREAD

**Issue by paul-reilly** [HerikLyma/CPPWebFramework#21]
Hi

Re issue #19 the problem appears to be only when building the example in Debug mode, when building Release it works perfectly.

The POST parameters are available for inspection via `request.getParameter` in `doPost`, but something is going wrong after that, so the results aren't shown in bmiresults.view .

**Comment by HerikLyma** [comment]
Hello Friend.

How are you?

Friend, apparently this problem is occurring only in Windows, in the other platforms it works normally. By the way I reprogrammed the .pro files so that qmake/make generates two versions of the library. One release and one debug. Please test this version.

Note: I will send you an email.


Thank you very much
Herik Lima

**Comment by paul-reilly** [comment]
Hi, thanks that fixes the issue and I have supplied the feedback. It's really nice having such an easy to use framework that uses C++ so thanks for all your good work!

**Comment by HerikLyma** [comment]
Hello my friend.

Thank you very much!
